name: Daily Commit

on:
  schedule:
    # Runs at 12:10 UTC (specific time as required)
    - cron: '10 12 * * *'
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  create-daily-commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Full git history needed for commits
          fetch-depth: 0
      
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "23f2000983@ds.study.iitm.ac.in"
      
      - name: Create daily commit with email 23f2000983@ds.study.iitm.ac.in
        run: |
          # Create or update the daily commit file
          echo "Last updated: $(date)" > daily-update.txt
          
          # Stage and commit the changes
          git add daily-update.txt
          git commit -m "Daily automatic commit $(date)"
          
          # Push the changes
          git push
